### PR TITLE
fix "mapped without a transient parent" Gtk warning in file chooser

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by multiSnow** [comment]
This warning should not appeared anymore since https://github.com/multiSnow/mcomix3/commit/8674950c119bf895e86095e17a86b46775358efd.

**Comment by ghost** [comment]
this is the file chooser for files from disk.

It appears in main"File>open"
and the library "right click > add"

**Comment by multiSnow** [comment]
For 'File>Open', https://github.com/multiSnow/mcomix3/blob/342b8ac74da5154373be12f53768585a101596b4/mcomix/mcomix/file_chooser_main_dialog.py#L17

For 'Add' in library, https://github.com/multiSnow/mcomix3/blob/342b8ac74da5154373be12f53768585a101596b4/mcomix/mcomix/file_chooser_library_dialog.py#L16

`set_transient_for(...)` is used here, which inherited from `Gtk.Window`, to set the parent window.
see https://lazka.github.io/pgi-docs/Gtk-3.0/classes/Window.html#Gtk.Window.set_transient_for

**Comment by ghost** [comment]
??? I still see the warning with latest gtk3 branch.

**Comment by ghost** [comment]
I still see the warnings, yet the windows are always on top as they should. Are you using Wayland by any chance? I'm using Mate/X.

According to this. The warning can still appear in X.
https://www.linuxquestions.org/questions/debian-26/%5Bsolved%5D-gtk-message-gtkdialog-mapped-without-a-transient-parent-this-is-discouraged-4175550278/#post5806730

I guess it's some little bug in gtk/X that we can ignore.

**Pull request closed without merging**
