### PR TITLE
fix openwith freezing the GUI

### PR DESCRIPTION
**Pull request by ghost**
fix openwith freezing the GUI
it seams popen is not compatible with "with"

### CODE REVIEW

**Comment by multiSnow** [comment]
context manager should be supported since python3.2, see https://docs.python.org/3/library/subprocess.html#subprocess.Popen for more infomation.

**Comment by ghost** [comment]
i meant, that when you launch a command that doesn't end immediately, the GUI freezes until the command finishes.

**Comment by multiSnow** [comment]
call `Popen` without cleanup is not a good idea. see https://github.com/python/cpython/blob/v3.4.0/Lib/subprocess.py#L890

yes, there's no need to use context manager, but at least we should call `wait()` in threading to ensure everything ends gracefully, or tell user something is still running.

**Comment by ghost** [comment]
@multiSnow 

When an exception occurs in the thread, it is not caught by the try.
It just sees thread.start immediately  return successfully.
There's no simple solution to this.

I had peaked in an other project with a similar problem, and they simply had removed the with.

Since these are user defined commands. It seams best to simply remove the with, and let the user deal with the errors.

**Comment by multiSnow** [comment]
I agree with you that, it is not a good idea to use `threading` while to except something, and one way to do that by providing a new `Thread.run` will terribly mess up everything.

From the original mcomix, `stdout` and `stderr` is set to `NULL`, so nothing from command will shows to user, nor the exit code from command.
So, the only situation to raise exception by `call` is command not found or not executable, and it should already been tested by `OpenWithCommand.is_executable`.
That is to say, even in the original mcomix, `process.popen` should not raise exception by itself.

And, by using `threading` or something (maybe `asyncio`?) other than `Popen` directly, it will be a chance to catch it again to show user if command is still running or finished successfully without blocking the hole application. Let's hold the dream and possibility, please.

**Pull request closed without merging**
