### PR TITLE
Allow creating up to 20 custom commands instead of 9

### PR DESCRIPTION
**Pull request by brunoais**

### CODE REVIEW

**Comment by brunoais** [comment]
Why is it refused?

**Comment by wyatt8740** [comment]
Just reading the code, I can't tell how this works. Most keyboards don't have a '10' key. What key would be bound to the command after the one for the '9' key?

**Comment by brunoais** [comment]
The way this works is very tied to the original code. By allowing more numbers to the `execute_command_`, more custom commands can be registered.

Feel free to ask me more questions or challenge my code.

**As for the default shortcuts for the custom commands:**
By default, no key is bound beyond the 9. However, the user is free to bound one himself.
There are many options we can go from there. 
1. Keep as I did (nothing is bound by default)
2. We can add a modifier, such as `Shift` or `Ctrl` and continue counting

Whichever you choose, I'm willing to go with it.

**Comment by wyatt8740** [comment]
Ah, I see. This might be something I use in my personal tweaked version, then.

I am not the one who closed this (and I have no power here), though.

**Comment by brunoais** [comment]
It's still sad to just get a rejected and no recourse

**Comment by brunoais** [comment]
@multiSnow Thank you for explaining why. Unfortunately, I didn't get any notification about your reference in the commit so it was now I was checking out what was new to merge locally that I noticed what you did.
For the next time please state a reason. For this time, it could be of sorts:

> I'm currently working on a feature that clashes with your changes/implementation. I'll give news when I have it ready

Just that is enough of a justification :). But the past is the past... It cannot be changed. The future is the one where we can know more ^^

**Pull request closed without merging**
